# Generated by Django 5.2 on 2025-04-27 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_user_bio_user_games_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='unknown', max_length=255),
        ),
    ]
