# Generated by Django 5.2 on 2025-05-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_user_full_name'),
        ('games', '0002_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='games',
        ),
        migrations.AddField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(blank=True, to='games.game'),
        ),
    ]
