# Generated by Django 5.2 on 2025-05-10 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_user_games_user_games'),
        ('games', '0005_match_player1_points_match_player2_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='games',
            field=models.ManyToManyField(blank=True, related_name='users', to='games.game'),
        ),
    ]
