# Generated by Django 5.2 on 2025-04-28 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('icon', models.CharField(blank=True, max_length=10)),
                ('players', models.IntegerField(default=0)),
                ('matches', models.IntegerField(default=0)),
            ],
        ),
    ]
