# Generated by Django 5.2 on 2025-05-09 03:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
        ('games', '0003_match_ended_at_match_started_at_match_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.challenge'),
        ),
    ]
