# Generated by Django 5.2 on 2025-05-09 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_match_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_points',
            field=models.IntegerField(default=0),
        ),
    ]
