# Generated by Django 5.2 on 2025-05-16 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_match_player1_points_match_player2_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='extra_stats',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
