# Generated by Django 5.2 on 2025-05-17 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_alter_tennismatch_challenge'),
        ('games', '0006_match_extra_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='challenge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='match', to='challenges.challenge'),
        ),
    ]
