# Generated by Django 5.2 on 2025-05-13 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='guest_players',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(default='singles', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='player1_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='match',
            name='status',
            field=models.CharField(default='not_started', max_length=30),
        ),
        migrations.AlterField(
            model_name='match',
            name='game_type',
            field=models.CharField(choices=[('tennis', 'Tennis'), ('badminton', 'Badminton'), ('chess', 'Chess'), ('tt', 'Table Tennis'), ('cricket', 'Cricket'), ('football', 'Football')], max_length=50),
        ),
    ]
