# Generated by Django 5.2 on 2025-05-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_match_player1_alter_match_player2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='winner_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
