# Generated by Django 5.2 on 2025-05-14 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0004_match_winner_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='sets',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
