# Generated by Django 5.2 on 2025-05-14 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0005_match_sets'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='player1_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='player2_points',
            field=models.IntegerField(default=0),
        ),
    ]
