# Generated by Django 5.2 on 2025-05-15 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0006_match_player1_points_match_player2_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='played_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
