# Generated by Django 5.2 on 2025-05-15 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0007_alter_match_played_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='score',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
