# Generated by Django 5.2 on 2025-05-15 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0008_alter_match_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='extra_stats',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
