# Generated by Django 5.2 on 2025-05-15 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0009_match_extra_stats'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='is_guest',
            field=models.BooleanField(default=False),
        ),
    ]
