# Generated by Django 5.2 on 2025-05-09 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tennismatch',
            name='challenge',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tennismatch', to='challenges.challenge'),
        ),
    ]
